# Generated by Django 5.0 on 2024-04-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("aid", models.AutoField(primary_key=True, serialize=False)),
                ("assignment_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("marks", models.IntegerField()),
                (
                    "aid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apigateway.assignment",
                    ),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apigateway.user",
                    ),
                ),
            ],
        ),
    ]
